refs/Product-design-principles.md

close https://github.com/blindnet-io/communication-management/issues/60

docs: add Privacy UX Enforcement Principle

---

refs/Product-design-choices.md

I propose to make a written Design Choice about how we treat password strenght, in order to have clear principles that can apply in the desing and that don't have to rediscussed all the time.
The idea is to support client systems that might need to operate under different regulations that may impose privacy-strenght policies.

Adding a principle for password strenght. Closes #674

---

specifications/Privateform-FRD.md
specifications/blindnet-FRD.md

Convert blindnet-FRD and Privateform-FRD to markdown and added them to the specifications folder.
Close https://github.com/blindnet-io/devrel-management/issues/22

Add blindnet-FRD and Privateform-FRD to specifications folder

---

refs/notion-of-privacy/principles/RFC-SPEP.md

Generalisation over theretic notions and different principles imposed by regulation.

Simple Privacy Engineering Principles

---

refs/high-level-architecture/readme.md
specifications/architecture/README.md

Language sycnchnonisation
- typos
- links
- Legal Ground -> Legal Base

language synchonisation

---

refs/Product-design-principles.md

Add antiperfectionism principle to product design principles

add antiperfectionism to design principles

---

.github/ISSUE_TEMPLATE/epic.md
.github/ISSUE_TEMPLATE/request.yml
.github/ISSUE_TEMPLATE/simple-task.md
.github/ISSUE_TEMPLATE/smart.md

Add issue templates from the communication-management repository (epic, request, simple task and smart goal).
this project would still need some additional specific issues and PR templates (see https://github.com/blindnet-io/devrel-management/issues/2)

build: add issue templates

---

specifications/frd/README.md

First draft of FRD. An example of FR for each component. Please add more following the example. 
Close #754

Functional Requirements Document

---

specifications/frd/README.md

> follows #755 & #754
- typos
- language harmonization with vocabulary
- missing RF numbers

Update DevKit Functional Requirements

---

specifications/README.md

as discussed in #754
close #771

docs: record new specification process

---

refs/Product-design-choices.md

Added Form validation update from https://github.com/blindnet-io/product-management/issues/303 in Product-design-choices.md document

Add Form validation update in Product-design-choices.md

---

specifications/Diagrams-Sketches-Privacy-Request-Capture-Interface.md

See https://github.com/blindnet-io/product-management/issues/720
See https://github.com/blindnet-io/product-management/issues/803
Define Diagrams and Sketches for Local Privacy Request Capture Interface TRANSPARENCY request
The goal is to have : 
- diagrams and sketches for local service 
- one diagram and sketches for TRANSPARENCY demand (action) illustrating the eligible scope for each demand regarding data categories, processing categories, purposes, and other elements
Document : [Figma link to diagrams and sketches](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=0%3A1)
See #734
Close #734

Define Diagrams and Sketches for Local Privacy Request Capture Interface and TRANSPARENCY request

---

decisions/01-DR-Lost-password-reset.md
user-stories/Notes_06-Lost-password-reset.md
user-stories/Notes_Lost-password-reset.md
user-stories/US-06-Lost-password-reset.md

Create 01-DR-Lost-password-reset

Lost password reset

---

user-stories/US-08-Data-Consumer-interface.md

Define User Stories for [Data Consumer Interface](https://github.com/blindnet-io/product-management/tree/main/refs/high-level-architecture#data-consumer-interface)
See https://github.com/blindnet-io/product-management/issues/756
Close #757

Define-US-for-Data-Consumer-interface

---

refs/schemas/priv/RFC-PRIV.md

Allow PRIV objects (in addition to PRIV terms) as values for `answers`

---

specifications/Diagrams-Sketches-Privacy-Request-Capture-Interface.md

This work is part of https://github.com/blindnet-io/product-management/issues/720
And is a subtask of https://github.com/blindnet-io/product-management/issues/803
Goal
Make Diagrams and Sketches for local REVOKE-CONSENT demand
Document : [Figma link to diagrams and sketches](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=651%3A372)
Close https://github.com/blindnet-io/product-management/issues/805

Define Diagrams and Sketches for local REVOKE-CONSENT demand

---

.github/ISSUE_TEMPLATE/1-bug.yaml
.github/ISSUE_TEMPLATE/2-feature-request.yaml
.github/ISSUE_TEMPLATE/3-docs.yaml
.github/ISSUE_TEMPLATE/4-request.yml
.github/ISSUE_TEMPLATE/5-project.md
.github/ISSUE_TEMPLATE/6-epic.md
.github/ISSUE_TEMPLATE/7-simple-task.md
.github/ISSUE_TEMPLATE/8-smart.md
README.md

Add new issue templates for bugs, feature/enhancement requests, etc.
README has also been simplified a little to give more incentive to contribute using these templates.

reorganise and add new issue templates

---

specifications/Diagrams-Sketches-Privacy-Request-Capture-Interface.md

Update the sketches for the following issues : 
- https://github.com/blindnet-io/privacy-components-web/issues/23
- https://github.com/blindnet-io/privacy-components-web/issues/20
- https://github.com/blindnet-io/privacy-components-web/issues/19
Here is the [Figma document link](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=0%3A1)
Close https://github.com/blindnet-io/product-management/issues/853
Close https://github.com/blindnet-io/product-management/issues/854
Close https://github.com/blindnet-io/product-management/issues/855

Update Sketches for Privacy Request Capture Interface

---

specifications/Diagrams-Sketches-Privacy-Request-Capture-Interface.md

Make sketches for answers for DELETE, ACCESS, REVOKE-CONSENT demands
- DELETE: [figma sketches](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=851%3A461)
- ACCESS: [figma sketches](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=853%3A425)
- REVOKE-CONSENT:[ figma sketches](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=853%3A330)
Close #864

Sketches for answers for DELETE, ACCESS, REVOKE-CONSENT demands

---

specifications/Diagrams-Sketches-Data-Consumer-Interface.md

See https://github.com/blindnet-io/product-management/issues/756
See https://github.com/blindnet-io/product-management/issues/857
Make Diagrams and Sketches for the Data Consumer Interface
Document : [Figma link to diagrams and sketches](https://www.figma.com/file/1hX1hlUrq0QTDjMmLJrDSK/Data-Consumer-Interface)
See https://github.com/blindnet-io/product-management/issues/758
Close https://github.com/blindnet-io/product-management/issues/758

Define Diagrams and Sketches for the Data Consumer Interface
